### ISSUE TITLE
Laravel 5.8 Class blade.compiler does not exist

### ISSUE THREAD

**Issue by brandonsimpson** [akalongman/laravel-lodash#6]
After adding the service provider Longman\LaravelLodash\LodashServiceProvider::class, the application throws the error "Class blade.compiler does not exist". 

In the LodashServiceProvider.php it is loading $this->registerBladeDirectives(); in the register() method instead of the boot() method. Laravel 5.8 requires blade directives to be loaded in the boot method.

https://laravel.com/docs/5.8/blade#extending-blade

**Comment by brandonsimpson** [comment]
Seems like this is fixed on master but composer require defaults to 1.0.2

**Comment by akalongman** [comment]
I will release master as 2.x version and will be fixed
